parameters:
    excel_uploader.class: K2\UploadExcelBundle\Service\ExcelReader

services:
    excel_reader:
        class: %excel_uploader.class%
        arguments: 
            - "@form.factory"
            - "@event_dispatcher"
            - %kernel.root_dir%
