parameters:
    excel_uploader.class: K2\UploadExcelBundle\Service\ExcelReader
    excel_validator.class: K2\UploadExcelBundle\Service\Validator
    upload_excel.twig.extension.form.class: K2\UploadExcelBundle\Twig\Extension\FormExtension

services:
    excel_reader:
        class: %excel_uploader.class%
        arguments: 
            - "@form.factory"
            - "@event_dispatcher"
        calls:
          -  [ setValidator, [ "@excel_validator" ] ]
    excel_validator:
        class: %excel_validator.class%
        arguments: 
            - "@validator"
    upload_excel.twig.extension.form:
        class: %upload_excel.twig.extension.form.class%
        arguments: 
            - "@twig.form.renderer"
        tags:
           - { name: twig.extension }
